### ISSUE TITLE
Regression in version 1.1.8 when creating connection

### ISSUE THREAD

**Issue by villebro** [snowflakedb/snowflake-sqlalchemy#80]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6.7 (Linux), 3.7.2 (MacOS)

2. What operating system and processor architecture are you using?
Linux, MacOS

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Creating a connection to "snowflake://USER:PASSWORD@HOSTNAME/DATABASE?warehouse=WAREHOUSE" yields 
`Connection failed!\n\nThe error message returned was:\ncannot import name 'NoneType' from 'types'` (py 3.7.2 on MacOS)
`Connection failed!\n\nThe error message returned was:\ncannot import name 'NoneType'` (py 3.6.7 on Ubuntu 18.04 LTS)

The problem was seen on Apache Superset after upgrading to 1.1.8.

5. What did you expect to see?
Works correctly on 1.1.6, but gives the above error on 1.1.8.

If you are unable to reproduce I can provide a script to replicate the error.

**Comment by smtakeda** [comment]
Sorry about inconvenience. For now, 1.1.8 was dropped. Due to miscommunication with the release team, an incomplete package was released. Github code should be good. Will fix the pypi package tomorrow.

**Comment by villebro** [comment]
Thanks @smtakeda for fixing this.
