### ISSUE TITLE
SNOW-1871582: Array support broken in 1.7.2

### ISSUE THREAD

**Issue by jochenott** [snowflakedb/snowflake-sqlalchemy#567]
1. What version of Python are you using? 3.12
2. What operating system and processor architecture are you using? osx-arm64
3. What are the component versions in the environment (`pip freeze`)?
  snowflake-sqlalchemy 1.7.2 and sqlalchemy 1.X

4. What did you do? Compile a "create table" statement for a table that contains a column with "array" type.
5. What did you expect to see? No exception. Instead, there was an exception.

To reproduce:

```python
from snowflake.sqlalchemy.snowdialect import SnowflakeDialect
import sqlalchemy as sa

dialect = SnowflakeDialect()

table = sa.Table(
    "table",
    sa.MetaData(),
    sa.Column(
        "array_str_column",
        sa.ARRAY(sa.String),
    ),
)
create_table = sa.sql.ddl.CreateTable(table)
print(str(create_table.compile(dialect=dialect)))
```
This worked for snowflake-sqlalchemy 1.7.1 without raising an exception.

For snowflake-sqlalchemy 1.7.2, this results in an exception `AttributeError: 'ARRAY' object has no attribute 'is_semi_structured'` pointing to this line as the culprit of the attribute error:
https://github.com/snowflakedb/snowflake-sqlalchemy/blob/115da35aee57a6a65ab774e19770cdf8ff386fba/src/snowflake/sqlalchemy/base.py#L1099

This code was introduced in #560 .

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for raising this issue with us. We regret seeing how much issues you have with this library and will work on rectifying it. The issue is now with the dev team who will take a look.

**Comment by sfc-gh-dszmolka** [comment]
fixed with https://github.com/snowflakedb/snowflake-sqlalchemy/pull/568, awaiting release

**Comment by sfc-gh-dszmolka** [comment]
released with snowflake-sqlalchemy 1.7.3
